<a href="https://colab.research.google.com/github/bezawadasandeep/ML-WORK-SHEET/blob/main/Logistic_Regression_6.6_1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [8]:
df = pd.read_excel("Graduate_Admission_Logistic_Regression_Dataset.xlsx")

In [9]:
df.head()

   GRE   GPA  Rank  Admit
0  301  3.90     4      0
1  269  3.64     1      1
2  267  3.82     2      1
3  315  2.84     2      1
4  314  2.12     1      0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GRE     1000 non-null   int64
 1   GPA     1000 non-null   float64
 2   Rank    1000 non-null   int64
 3   Admit   1000 non-null   int64
dtypes: float64(1), int64(3)
memory usage: 31.4 KB

In [11]:
df.isnull().sum()

GRE      0
GPA      0
Rank     0
Admit    0
dtype: int64

In [12]:
df.describe()

               GRE          GPA         Rank        Admit
count  1000.000000  1000.000000  1000.000000  1000.000000
mean    298.983000     2.998020     2.495000     0.533000
std      23.332319     0.590419     1.115894     0.499159
min     260.000000     2.000000     1.000000     0.000000
25%     278.000000     2.470000     2.000000     0.000000
50%     299.000000     3.020000     2.000000     1.000000
75%     319.000000     3.510000     3.000000     1.000000
max     340.000000     4.000000     4.000000     1.000000

In [13]:
X = df[['GRE','GPA','Rank']]
y = df['Admit']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
model = LogisticRegression(max_iter=1000)

In [16]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [17]:
y_pred = model.predict(X_test)

In [18]:
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.675

In [19]:
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[55 35]
 [30 80]]

In [20]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.61      0.63        90
           1       0.70      0.73      0.71       110

    accuracy                           0.68       200
   macro avg       0.67      0.67      0.67       200
weighted avg       0.67      0.68      0.67       200

In [21]:
new_student = [[320, 3.75, 2]]

prediction = model.predict(new_student)

print("Prediction:", prediction)

Prediction: [1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [22]:
probability = model.predict_proba(new_student)

print(probability)

[[0.16592783 0.83407217]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [23]:
print("Intercept:", model.intercept_)
print("Coefficients:", model.coef_)

Intercept: [-10.04086721]
Coefficients: [[ 0.02839919  0.89003828 -0.3848747 ]]